name: deploy-orders

on:
  push:
    branches:
      - main
    paths:
      - 'orders/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run docker build command
        run: cd orders && docker build -t amolbkgunjal/orders .
      - name: login to docker hub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD        
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Run docker push command to push into the docker hub
        run: docker push amolbkgunjal/orders
#       - uses: digitalocean/action-doctl@v2
#         with:
#           token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
#       - name: doctl load the config of kubernetes in git hub container and set the digital ocean context
#         run: doctl kubernetes cluster kubeconfig save ticketing
#       - name: restart the deployment
#         run: kubectl rollout restart deployment orders-depl
