name: tests-orders

on:
  pull_request:
    paths:
      - 'orders/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a auth service tests
        run: cd orders && npm install && npm run test:ci
